# SPDX-License-Identifier: Apache-2.0
"""Read-only accessor for the checked-in model download-size manifest.

The manifest (``model_sizes.json``, generated by
``scripts/gen_model_sizes.py``) maps each ``hf_path`` to its weight+tokenizer
download footprint in bytes. It lets ``rapid-mlx models`` show a ``Size``
column and ``rapid-mlx info <alias>`` show a size line WITHOUT a per-invocation
HuggingFace round-trip — the listing stays instant and works offline.

Sizes are the same footprint the download-confirmation gate reports
(``_download_gate.estimate_repo_size_bytes``), so the table and the ``[Y/n]``
prompt agree. They are an APPROXIMATE hint captured at manifest-generation
time — the authoritative footprint is the live gate at pull time.

Three states, deliberately distinguished:

* key present with a positive int  → a known size.
* key present with ``null``        → LISTED but unresolvable at generation
  time (e.g. a 404/gated repo). ``size_bytes`` returns ``None`` but
  ``is_listed`` returns True, so callers can skip a pointless live re-probe.
* key absent                       → an hf_path the registry doesn't carry
  (e.g. a raw repo a user typed); ``is_listed`` is False.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from ._download_gate import _format_size

_MANIFEST_PATH = Path(__file__).with_name("model_sizes.json")


@lru_cache(maxsize=1)
def _raw() -> dict[str, int | None]:
    """Load ``hf_path -> bytes|None`` once, preserving ``null`` entries.

    Missing / corrupt / wrong-shape manifest → empty map (the listing degrades
    to "—" rather than crashing). Non-positive / non-int values are normalised
    to ``None`` so a hand-edited or malformed size can never render as a bogus
    footprint.
    """
    try:
        raw = json.loads(_MANIFEST_PATH.read_text())
    except (OSError, ValueError):
        return {}
    sizes = raw.get("sizes") if isinstance(raw, dict) else None
    if not isinstance(sizes, dict):
        return {}
    out: dict[str, int | None] = {}
    for k, v in sizes.items():
        if not isinstance(k, str):
            continue
        out[k] = (
            v if (isinstance(v, int) and not isinstance(v, bool) and v > 0) else None
        )
    return out


def is_listed(hf_path: str) -> bool:
    """True if ``hf_path`` has a manifest entry (even an unresolvable ``null``).

    Lets callers tell "we already know we can't size this" (skip the network)
    apart from "never seen this repo" (a live probe may be worthwhile).
    """
    return hf_path in _raw()


def size_bytes(hf_path: str) -> int | None:
    """Download footprint of ``hf_path`` in bytes, or ``None`` if unknown."""
    return _raw().get(hf_path)


def format_size(hf_path: str, *, unknown: str = "—") -> str:
    """Human-friendly size for ``hf_path`` (e.g. ``141.1 GiB``), else ``unknown``.

    Uses the same base-1024 formatter as the download gate so ``rapid-mlx
    models`` and the ``[Y/n]`` prompt render identical strings.
    """
    n = size_bytes(hf_path)
    return _format_size(n) if n is not None else unknown
