# SPDX-License-Identifier: Apache-2.0
"""Tests for ``rapid-mlx convert`` — the GGUF → MLX pipeline.

The fixture is a tiny synthetic llama-arch GGUF (2 layers, dim 64, GQA
4/2 heads, 256-token BPE vocab) written with ``gguf.GGUFWriter`` — f16
tensors carrying small-integer values (exactly representable in bf16, so
the round trip is asserted with zero tolerance) plus Q4_0 tensors asserted
against ``gguf.quants.dequantize`` within quantization tolerance.

Nothing here touches the network: HF-hub source resolution is exercised
with a mocked ``snapshot_download``, and the base-model config/tokenizer
strategy with a fabricated local "hub" directory. The one test that needs
a real download is marked ``slow`` and deselected by default.
"""

from __future__ import annotations

import io
import json
import sys
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import mlx.core as mx
import numpy as np
import pytest
from gguf import GGMLQuantizationType, GGUFWriter
from gguf.quants import dequantize, quantize

from vllm_mlx import cli
from vllm_mlx.gguf_convert import (
    ConvertError,
    _resolve_source,
    convert_command,
    convert_gguf,
)

# ----- tiny GGUF fixture ----------------------------------------------------

_DIM = 64
_LAYERS = 2
_FFN = 128
_HEADS = 4
_KV_HEADS = 2
_CTX = 128
_VOCAB = 256

# Deterministic value source; small integers are exact in f16/bf16/f32, so
# f16 tensors can be asserted with zero tolerance after the round trip.
_RNG = np.random.default_rng(20260721)


def _exact_f16(shape: tuple[int, ...]) -> np.ndarray:
    return _RNG.integers(-3, 4, size=shape).astype(np.float32).astype(np.float16)


def _q4_0(shape: tuple[int, ...]) -> np.ndarray:
    """Quantize a random f32 tensor to Q4_0 bytes (last dim must be %32)."""
    assert shape[-1] % 32 == 0
    return quantize(
        _RNG.standard_normal(shape).astype(np.float32), GGMLQuantizationType.Q4_0
    )


# Tensors of the fixture: (ggml_name, kind, numpy_logical_shape). Values are
# regenerated by the same seeded RNG in _expected_weights() below — order of
# generation must match exactly between the two.
_LAYOUT: list[tuple[str, str, tuple[int, ...]]] = [
    ("token_embd.weight", "f16", (_VOCAB, _DIM)),
]
for _i in range(_LAYERS):
    _LAYOUT += [
        (f"blk.{_i}.attn_norm.weight", "f16", (_DIM,)),
        (f"blk.{_i}.attn_q.weight", "q4_0", (_DIM, _DIM)),
        (f"blk.{_i}.attn_k.weight", "f16", (_DIM // _HEADS * _KV_HEADS, _DIM)),
        (f"blk.{_i}.attn_v.weight", "f16", (_DIM // _HEADS * _KV_HEADS, _DIM)),
        (f"blk.{_i}.attn_output.weight", "f16", (_DIM, _DIM)),
        (f"blk.{_i}.ffn_norm.weight", "f16", (_DIM,)),
        (f"blk.{_i}.ffn_gate.weight", "q4_0", (_FFN, _DIM)),
        (f"blk.{_i}.ffn_up.weight", "f16", (_FFN, _DIM)),
        (f"blk.{_i}.ffn_down.weight", "f16", (_DIM, _FFN)),
    ]
_LAYOUT += [
    ("output_norm.weight", "f16", (_DIM,)),
    # Deliberately no ``output.weight``: exercises the tie_word_embeddings
    # detection (llama.cpp omits the output tensor for tied models).
]


def _make_tensors() -> dict[str, tuple[np.ndarray, str]]:
    """Regenerate the fixture's tensor values (seeded → deterministic)."""
    rng = np.random.default_rng(20260721)
    out: dict[str, tuple[np.ndarray, str]] = {}
    for name, kind, shape in _LAYOUT:
        if kind == "f16":
            out[name] = (
                rng.integers(-3, 4, size=shape).astype(np.float32).astype(np.float16),
                kind,
            )
        else:
            out[name] = (
                quantize(
                    rng.standard_normal(shape).astype(np.float32),
                    GGMLQuantizationType.Q4_0,
                ),
                kind,
            )
    return out


def _write_tiny_gguf(
    path: Path, base_repo: str | None = None
) -> dict[str, tuple[np.ndarray, str]]:
    """Write the tiny llama GGUF; returns ``{ggml_name: (data, kind)}``."""
    tensors = _make_tensors()
    w = GGUFWriter(str(path), arch="llama")
    w.add_name("tiny-llama-fixture")
    w.add_context_length(_CTX)
    w.add_embedding_length(_DIM)
    w.add_block_count(_LAYERS)
    w.add_feed_forward_length(_FFN)
    w.add_head_count(_HEADS)
    w.add_head_count_kv(_KV_HEADS)
    w.add_layer_norm_rms_eps(1e-5)
    w.add_rope_freq_base(10000.0)
    w.add_vocab_size(_VOCAB)
    # Minimal byte-level-BPE-shaped vocab plus two merge products (BPE
    # requires the *result* of every merge rule to be in the vocab), so
    # transformers' converter takes the BPE (not the scores) branch.
    # bos/eos/unk map onto the first three tokens.
    tokens = (
        ["<s>", "</s>", "<unk>"]
        + [f"t{i}" for i in range(_VOCAB - 5)]
        + ["t3t4", "t5t6"]
    )
    w.add_tokenizer_model("gpt2")
    w.add_tokenizer_pre("default")
    w.add_token_list(tokens)
    w.add_token_merges(["t3 t4", "t5 t6"])
    w.add_bos_token_id(0)
    w.add_eos_token_id(1)
    w.add_unk_token_id(2)
    if base_repo is not None:
        w.add_base_model_count(1)
        w.add_base_model_repo_url(0, f"https://huggingface.co/{base_repo}")
    w.add_file_type(int(GGMLQuantizationType.F16))
    for name, kind, _shape in _LAYOUT:
        data, _ = tensors[name]
        if kind == "q4_0":
            w.add_tensor(name, data, raw_dtype=GGMLQuantizationType.Q4_0)
        else:
            w.add_tensor(name, data)
    w.open_output_file()
    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()
    return tensors


@pytest.fixture(scope="module")
def tiny_gguf(tmp_path_factory) -> Path:
    path = tmp_path_factory.mktemp("gguf") / "tiny-llama.gguf"
    _write_tiny_gguf(path)
    return path


@pytest.fixture(scope="module")
def converted(tmp_path_factory, tiny_gguf) -> Path:
    """Run the full-precision conversion once per module."""
    out = tmp_path_factory.mktemp("out") / "tiny-mlx"
    convert_gguf(str(tiny_gguf), out_dir=out, report=False)
    return out


@pytest.fixture(scope="module")
def converted_4bit(tmp_path_factory, tiny_gguf) -> tuple[Path, object]:
    """Run the ``--bits 4`` path (requant + perplexity report) once."""
    out = tmp_path_factory.mktemp("outq") / "tiny-mlx-4bit"
    result = convert_gguf(str(tiny_gguf), out_dir=out, bits=4)
    return out, result


@pytest.fixture(autouse=True)
def _generation_stream_on_current_thread(monkeypatch):
    """Pin ``mlx_lm.generate.generation_stream`` to this thread's default stream.

    mlx-lm 0.31.3 captures ``generation_stream = mx.new_thread_local_stream(...)``
    at *module-import* time (``mlx_lm/generate.py:226``). In the full suite,
    earlier engine-booting tests (e.g. ``test_cli_bench.py``'s
    ``bench_command``) import ``mlx_lm.generate`` on a *worker* thread; via
    ``vllm_mlx._mlx_compat``'s patched factory the captured handle is the
    worker's plain default stream (``Stream(gpu, 1)`` — see the
    ``engine_core`` "worker default = generation_stream" boot log). Once the
    worker exits, the main thread cannot eval that handle: any later
    main-thread ``mlx_lm.generate()`` dies at prefill with
    ``RuntimeError: There is no Stream(gpu, N) in current thread.``
    (#720 family; empirical contract in
    ``tests/test_mllm_cross_thread_stream_contract.py``).

    The repo's sanctioned remedy is ``engine_core._init_mlx_step_thread``'s
    shim: reassign the module attribute to the *current* thread's
    process-wide default stream (``mx.default_stream(mx.default_device())``)
    — "the only path that round-trips cleanly across threads". Applying it
    before every test here makes ``generate()`` immune to whatever stream
    state earlier suite members leave behind; standalone runs are unaffected
    and ``monkeypatch`` restores the captured value at teardown.
    """
    import importlib

    import mlx.core as mx

    gen_mod = importlib.import_module("mlx_lm.generate")
    monkeypatch.setattr(
        gen_mod, "generation_stream", mx.default_stream(mx.default_device())
    )


# ----- config.json ----------------------------------------------------------


def test_config_json_fields(converted):
    cfg = json.loads((converted / "config.json").read_text())
    assert cfg["model_type"] == "llama"
    assert cfg["hidden_size"] == _DIM
    assert cfg["intermediate_size"] == _FFN
    assert cfg["num_hidden_layers"] == _LAYERS
    assert cfg["num_attention_heads"] == _HEADS
    assert cfg["num_key_value_heads"] == _KV_HEADS
    assert cfg["vocab_size"] == _VOCAB
    assert cfg["max_position_embeddings"] == _CTX
    assert cfg["rope_theta"] == 10000.0
    assert cfg["rms_norm_eps"] == pytest.approx(1e-5)
    # No rope.dimension_count / attention.key_length in the fixture →
    # head_dim falls back to hidden_size // num_attention_heads.
    assert cfg["head_dim"] == _DIM // _HEADS
    # No output.weight in the fixture → tied embeddings must be inferred.
    assert cfg["tie_word_embeddings"] is True
    # torch_dtype records the *written* dtype, default bfloat16.
    assert cfg["torch_dtype"] == "bfloat16"
    assert cfg["architectures"] == ["LlamaForCausalLM"]


# ----- tokenizer ------------------------------------------------------------


def test_tokenizer_roundtrip(converted):
    from transformers import AutoTokenizer

    assert (converted / "tokenizer.json").is_file()
    tok = AutoTokenizer.from_pretrained(str(converted))
    assert tok.bos_token_id == 0
    assert tok.eos_token_id == 1
    ids = tok.encode("t3 t4 t5")
    assert ids and tok.decode(ids)
    # Merges from the GGUF must be live: t3+t4 collapses to a single token.
    assert tok.convert_tokens_to_ids("t3") is not None


def test_bos_post_processing_from_gguf_flags(converted, tmp_path):
    """BOS handling follows the GGUF flags, not converter defaults:
    the llama fixture (no add_bos_token field, non-qwen2 pre) mirrors
    llama.cpp's add-BOS default; a qwen2-pre GGUF must NOT add BOS."""
    import gguf
    from transformers import AutoTokenizer

    from vllm_mlx.gguf_convert import _write_tokenizer_from_gguf

    tok = AutoTokenizer.from_pretrained(str(converted))
    ids = tok.encode("t3 t4")
    assert ids[0] == 0, f"llama-family default should prepend bos (<s>=0): {ids}"

    path = tmp_path / "q3tok.gguf"
    _write_qwen3_style_gguf(path)
    out = tmp_path / "q3tok"
    out.mkdir()
    _write_tokenizer_from_gguf(gguf.GGUFReader(str(path)), "qwen3", out)
    # Structural check (the synthetic qwen2 vocab is not byte-level-faithful
    # enough for a meaningful encode round-trip): the saved tokenizer.json
    # must carry NO bos-prepending TemplateProcessing.
    tj = json.loads((out / "tokenizer.json").read_text())
    pp = json.dumps(tj.get("post_processor") or {})
    assert "<s>" not in pp, f"qwen2-style BPE must not prepend bos: {pp}"


def test_generation_config_stub(converted):
    gen = json.loads((converted / "generation_config.json").read_text())
    assert gen["bos_token_id"] == 0
    assert gen["eos_token_id"] == 1


def _write_qwen3_style_gguf(path: Path) -> None:
    """Minimal qwen3 GGUF (metadata only — config/name-map unit tests)."""
    w = GGUFWriter(str(path), arch="qwen3")
    w.add_context_length(_CTX)
    w.add_embedding_length(_DIM)
    w.add_block_count(_LAYERS)
    w.add_feed_forward_length(_FFN)
    w.add_head_count(_HEADS)
    w.add_head_count_kv(_KV_HEADS)
    w.add_layer_norm_rms_eps(1e-6)
    w.add_rope_freq_base(1000000.0)
    w.add_key_length(32)  # ≠ hidden//heads (16) on purpose
    w.add_tokenizer_model("gpt2")
    w.add_tokenizer_pre("qwen2")
    w.add_token_list(["<s>", "</s>"] + [f"t{i}" for i in range(252)] + ["t3t4"])
    w.add_token_merges(["t3 t4"])
    w.add_bos_token_id(0)
    w.add_eos_token_id(1)
    w.add_file_type(int(GGMLQuantizationType.F16))
    w.open_output_file()
    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()


def test_head_dim_prefers_explicit_key_length(tmp_path):
    """qwen3-style GGUFs carry attention.key_length; it must win over the
    hidden//heads fallback (mlx-lm's qwen3 ModelArgs requires head_dim)."""
    import gguf

    from vllm_mlx.gguf_convert import _build_config_from_gguf

    path = tmp_path / "kl.gguf"
    _write_qwen3_style_gguf(path)

    reader = gguf.GGUFReader(str(path))
    cfg = _build_config_from_gguf(reader, tie_word_embeddings=True)
    assert cfg["model_type"] == "qwen3"
    assert cfg["head_dim"] == 32
    assert cfg["num_key_value_heads"] == _KV_HEADS


def test_qwen3_qk_norm_maps_to_q_norm_not_q_layernorm(tmp_path):
    """mlx-lm expects ``self_attn.q_norm``; gguf's candidate table lists the
    persimmon ``q_layernorm`` variant first, so this pins the override."""
    import gguf

    from vllm_mlx.gguf_convert import _build_name_map

    path = tmp_path / "q3.gguf"
    _write_qwen3_style_gguf(path)
    reader = gguf.GGUFReader(str(path))
    name_map, _arch = _build_name_map(reader)
    assert name_map["blk.0.attn_q_norm"] == "model.layers.0.self_attn.q_norm"
    assert name_map["blk.0.attn_k_norm"] == "model.layers.0.self_attn.k_norm"


def _write_llama3_fingerprint_gguf(path: Path) -> None:
    """llama arch + theta=500000 + no rope.scaling.* — the Llama-3.x
    fingerprint older converters produce (hugging-quants Llama-3.2 Q8_0
    is exactly this shape)."""
    w = GGUFWriter(str(path), arch="llama")
    w.add_context_length(131072)
    w.add_embedding_length(_DIM)
    w.add_block_count(_LAYERS)
    w.add_feed_forward_length(_FFN)
    w.add_head_count(_HEADS)
    w.add_head_count_kv(_KV_HEADS)
    w.add_layer_norm_rms_eps(1e-5)
    w.add_rope_freq_base(500000.0)
    w.add_rope_dimension_count(_DIM // _HEADS)
    w.add_tokenizer_model("gpt2")
    w.add_tokenizer_pre("llama-bpe")
    w.add_token_list(["<s>", "</s>"] + [f"t{i}" for i in range(252)] + ["t3t4"])
    w.add_token_merges(["t3 t4"])
    w.add_bos_token_id(0)
    w.add_eos_token_id(1)
    w.add_file_type(int(GGMLQuantizationType.F16))
    w.open_output_file()
    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()


def test_llama3_rope_scaling_fingerprint(tmp_path):
    """theta=500000 llama GGUF without scaling fields must get the llama3
    block mlx-lm's Llama3RoPE needs (older converters omit it entirely)."""
    import gguf

    from vllm_mlx.gguf_convert import _build_config_from_gguf

    path = tmp_path / "l3.gguf"
    _write_llama3_fingerprint_gguf(path)
    cfg = _build_config_from_gguf(gguf.GGUFReader(str(path)), True)
    assert cfg["rope_scaling"] == {
        "rope_type": "llama3",
        "factor": 32.0,
        "low_freq_factor": 1.0,
        "high_freq_factor": 4.0,
        "original_max_position_embeddings": 8192,
    }
    # rope.dimension_count maps to head_dim via the upstream llama table.
    assert cfg["head_dim"] == _DIM // _HEADS


def test_plain_llama_gets_no_rope_scaling(tiny_gguf):
    """theta=10000 (Llama-2 style) must NOT grow a phantom scaling block."""
    import gguf

    from vllm_mlx.gguf_convert import _build_config_from_gguf

    cfg = _build_config_from_gguf(gguf.GGUFReader(str(tiny_gguf)), True)
    assert "rope_scaling" not in cfg


def test_llama_bpe_installs_canonical_pretokenizer(tmp_path):
    """pre=llama-bpe must install the official Llama-3 Split+ByteLevel
    pre-tokenizer (stock ByteLevel mis-segments punctuation/newline runs)."""
    import gguf

    from vllm_mlx.gguf_convert import _write_tokenizer_from_gguf

    path = tmp_path / "l3tok.gguf"
    _write_llama3_fingerprint_gguf(path)
    out = tmp_path / "l3tok"
    out.mkdir()
    _write_tokenizer_from_gguf(gguf.GGUFReader(str(path)), "llama", out)
    tj = json.loads((out / "tokenizer.json").read_text())
    pre = tj["pre_tokenizer"]
    assert pre["type"] == "Sequence"
    assert pre["pretokenizers"][0]["type"] == "Split"
    assert "\\p{N}{1,3}" in pre["pretokenizers"][0]["pattern"]["Regex"]
    # llama-bpe also implies add-BOS by the llama.cpp default.
    pp = json.dumps(tj.get("post_processor") or {})
    assert "<s>" in pp


# ----- weights ---------------------------------------------------------------


def test_weights_are_hf_named_and_complete(converted):
    weights = mx.load(str(converted / "model.safetensors"))
    names = set(weights)
    # Single shard for a tiny model → no index.json.
    assert not (converted / "model.safetensors.index.json").exists()
    expected = {
        "model.embed_tokens.weight",
        "model.norm.weight",
    }
    for i in range(_LAYERS):
        expected |= {
            f"model.layers.{i}.input_layernorm.weight",
            f"model.layers.{i}.self_attn.q_proj.weight",
            f"model.layers.{i}.self_attn.k_proj.weight",
            f"model.layers.{i}.self_attn.v_proj.weight",
            f"model.layers.{i}.self_attn.o_proj.weight",
            f"model.layers.{i}.post_attention_layernorm.weight",
            f"model.layers.{i}.mlp.gate_proj.weight",
            f"model.layers.{i}.mlp.up_proj.weight",
            f"model.layers.{i}.mlp.down_proj.weight",
        }
    assert names == expected
    # No ggml-style names leaked through.
    assert not any(n.startswith("blk.") for n in names)


def test_f16_values_exact_after_roundtrip(converted):
    from vllm_mlx.gguf_convert import _reverse_permute_qk

    tensors = _make_tensors()
    weights = {
        k: np.array(v.astype(mx.float32))
        for k, v in mx.load(str(converted / "model.safetensors")).items()
    }
    np.testing.assert_array_equal(
        weights["model.embed_tokens.weight"],
        tensors["token_embd.weight"][0].astype(np.float32),
    )
    # llama q/k are stored in GGUF's interleaved-rope layout; the converter
    # must apply the reverse permutation (transformers' LlamaTensorProcessor
    # semantics), so the expected value is the *unpermuted* fixture bytes.
    np.testing.assert_array_equal(
        weights["model.layers.1.self_attn.k_proj.weight"],
        _reverse_permute_qk(
            tensors["blk.1.attn_k.weight"][0].astype(np.float32), _HEADS, _KV_HEADS
        ),
    )
    np.testing.assert_array_equal(
        weights["model.norm.weight"],
        tensors["output_norm.weight"][0].astype(np.float32),
    )


def test_q4_0_values_within_quant_tolerance(converted):
    from vllm_mlx.gguf_convert import _reverse_permute_qk

    tensors = _make_tensors()
    weights = {
        k: np.array(v.astype(mx.float32))
        for k, v in mx.load(str(converted / "model.safetensors")).items()
    }
    # Expected values: dequantize the exact Q4_0 bytes the fixture carries
    # (q_proj additionally goes through the llama reverse permutation).
    expected_q = _reverse_permute_qk(
        dequantize(tensors["blk.0.attn_q.weight"][0], GGMLQuantizationType.Q4_0),
        _HEADS,
        _HEADS,
    )
    got_q = weights["model.layers.0.self_attn.q_proj.weight"]
    assert got_q.shape == expected_q.shape == (_DIM, _DIM)
    np.testing.assert_allclose(got_q, expected_q, rtol=0.02, atol=0.02)

    expected_g = dequantize(
        tensors["blk.1.ffn_gate.weight"][0], GGMLQuantizationType.Q4_0
    )
    got_g = weights["model.layers.1.mlp.gate_proj.weight"]
    assert got_g.shape == expected_g.shape == (_FFN, _DIM)
    np.testing.assert_allclose(got_g, expected_g, rtol=0.02, atol=0.02)


# ----- integration: mlx_lm actually loads the product ------------------------


def test_mlx_lm_loads_and_generates(converted):
    import mlx_lm

    model, tokenizer = mlx_lm.load(str(converted))
    text = mlx_lm.generate(
        model, tokenizer, prompt="t3 t4", max_tokens=4, verbose=False
    )
    assert isinstance(text, str) and len(text) > 0


# ----- --bits re-quantization + report --------------------------------------


def test_bits4_requant_produces_loadable_mlx_dir(converted_4bit):
    import mlx_lm

    out, result = converted_4bit
    cfg = json.loads((out / "config.json").read_text())
    # mlx_lm.convert stamps its quantization block into config.json.
    assert cfg.get("quantization", {}).get("bits") == 4
    assert cfg["torch_dtype"] == "bfloat16"
    assert any(out.glob("*.safetensors")), "quantized weights missing"
    assert (out / "tokenizer.json").is_file()

    model, tokenizer = mlx_lm.load(str(out))
    text = mlx_lm.generate(
        model, tokenizer, prompt="t3 t4", max_tokens=4, verbose=False
    )
    assert isinstance(text, str) and len(text) > 0
    assert result.bits == 4


def test_bits4_report_compares_bf16_vs_quant(converted_4bit):
    """--report defaults to on with --bits: ppl for both products is recorded.

    The fixture's weights are random, so the absolute ppl values are noise;
    what matters is that both passes ran and the delta was computed.
    """
    _out, result = converted_4bit
    rep = result.report
    assert rep is not None, "report should run by default when --bits is given"
    assert rep["ppl_reference"] > 0
    assert rep["ppl_candidate"] > 0
    assert rep["tokens"] > 0
    assert rep["candidate_label"] == "4-bit"
    expected_delta = (
        (rep["ppl_candidate"] - rep["ppl_reference"]) / rep["ppl_reference"] * 100
    )
    assert rep["delta_pct"] == pytest.approx(expected_delta)


def test_report_without_bits_is_skipped(tmp_path, tiny_gguf, capsys):
    """Asking for a report without --bits is a no-op with a printed note."""
    out = tmp_path / "fp"
    result = convert_gguf(str(tiny_gguf), out_dir=out, bits=None, report=True)
    assert result.report is None
    assert "report skipped" in capsys.readouterr().out


# ----- 1-bit source re-quantization warning ---------------------------------


def test_one_bit_source_quant_detection(monkeypatch):
    """The predicate reads ``general.file_type`` first (IQ1_M → named)."""
    from vllm_mlx import gguf_convert as gc

    monkeypatch.setattr(gc, "_field", lambda _r, _name: int(GGMLQuantizationType.IQ1_M))
    assert gc._one_bit_source_quant(SimpleNamespace()) == "IQ1_M"

    # Non-1-bit file_type falls through to the tensor-type majority vote
    # (empty tensor list → no majority → clean).
    monkeypatch.setattr(gc, "_field", lambda _r, _name: int(GGMLQuantizationType.Q4_0))
    assert gc._one_bit_source_quant(SimpleNamespace(tensors=[])) is None


def test_one_bit_requant_warns_on_stderr(tiny_gguf, tmp_path, capsys, monkeypatch):
    """1-bit source + --bits → loud stderr warning naming the source quant."""
    from vllm_mlx import gguf_convert as gc

    monkeypatch.setattr(gc, "_one_bit_source_quant", lambda _reader: "IQ1_M")
    convert_gguf(str(tiny_gguf), out_dir=tmp_path / "q", bits=4, report=False)
    err = capsys.readouterr().err
    assert "1-bit" in err and "IQ1_M" in err


def test_dense_source_requant_stays_quiet(tiny_gguf, tmp_path, capsys):
    """Ordinary sources (the Q4_0/f16 fixture) re-quantize with no warning."""
    convert_gguf(str(tiny_gguf), out_dir=tmp_path / "q", bits=4, report=False)
    assert "1-bit" not in capsys.readouterr().err


# ----- source resolution (mocked hub) ----------------------------------------


def test_resolve_local_file(tiny_gguf):
    assert _resolve_source(str(tiny_gguf)) == tiny_gguf


def test_resolve_rejects_non_gguf_file(tmp_path):
    bad = tmp_path / "model.bin"
    bad.write_bytes(b"nope")
    with pytest.raises(ConvertError, match="not a .gguf"):
        _resolve_source(str(bad))


def test_resolve_rejects_garbage_source():
    with pytest.raises(ConvertError, match="neither an existing local"):
        _resolve_source("definitely-not-a-repo-or-file")


# ----- hub-tags base-model detection + unified config flattening -----------


def test_base_repo_from_hub_tags(monkeypatch):
    from vllm_mlx import gguf_convert as gc

    def fake_api(tags):
        return SimpleNamespace(model_info=lambda _r: SimpleNamespace(tags=tags))

    monkeypatch.setattr(
        "huggingface_hub.HfApi",
        lambda: fake_api(
            [
                "gguf",
                "base_model:google/gemma-4-12B-it",
                "base_model:quantized:google/gemma-4-12B-it",
            ]
        ),
    )
    assert gc._base_repo_from_hub_tags("org/repo") == "google/gemma-4-12B-it"

    # quantized:/adapter: namespaces point at derived artifacts, not the base.
    monkeypatch.setattr(
        "huggingface_hub.HfApi",
        lambda: fake_api(
            ["base_model:quantized:org/derived", "base_model:adapter:org/lora"]
        ),
    )
    assert gc._base_repo_from_hub_tags("org/repo") is None

    # Hub errors (offline, gated repo) degrade to None → next strategy.
    monkeypatch.setattr(
        "huggingface_hub.HfApi",
        lambda: SimpleNamespace(
            model_info=lambda _r: (_ for _ in ()).throw(RuntimeError("boom"))
        ),
    )
    assert gc._base_repo_from_hub_tags("org/repo") is None


def test_flatten_unified_text_config():
    from vllm_mlx.gguf_convert import _flatten_unified_text_config

    unified = {
        "model_type": "gemma4",
        "text_config": {"num_key_value_heads": 8, "num_hidden_layers": 48},
        "other": 1,
    }
    flat = _flatten_unified_text_config(unified)
    assert flat["num_key_value_heads"] == 8
    assert flat["num_hidden_layers"] == 48
    assert flat["other"] == 1
    assert "text_config" not in flat
    # Non-nested configs pass through untouched.
    assert _flatten_unified_text_config({"a": 1}) == {"a": 1}


def test_scalar_int_coercions():
    from vllm_mlx.gguf_convert import _scalar_int

    assert _scalar_int(8, 1) == 8
    assert _scalar_int(None, 1) == 1
    # gemma4's per-layer KV-head list collapses to its max (see helper note).
    assert _scalar_int([8, 8, 1], 1) == 8
    assert _scalar_int([], 3) == 3


def test_untied_output_maps_to_bare_lm_head(tmp_path):
    """Untied models: ggml ``output.weight`` must map to bare ``lm_head``.

    gguf's candidate table also lists the legacy ``model.transformer.ff_out``
    name, which the generic "model.* first" rule preferred — mlx-lm then
    rejects the artifact at load time (Dolphin3.0 llama GGUF, untied).
    """
    from vllm_mlx.gguf_convert import _build_name_map

    gg = tmp_path / "untied.gguf"
    tensors = _make_tensors()
    w = GGUFWriter(str(gg), arch="llama")
    w.add_embedding_length(_DIM)
    w.add_block_count(_LAYERS)
    w.add_head_count(_HEADS)
    w.add_head_count_kv(_KV_HEADS)
    for name, kind, _shape in _LAYOUT:
        data, _ = tensors[name]
        if kind == "q4_0":
            w.add_tensor(name, data, raw_dtype=GGMLQuantizationType.Q4_0)
        else:
            w.add_tensor(name, data)
    w.add_tensor("output.weight", np.zeros((_VOCAB, _DIM), dtype=np.float16))
    w.open_output_file()
    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()

    from gguf import GGUFReader

    mapping, _ = _build_name_map(GGUFReader(str(gg)))
    assert mapping["output"] == "lm_head"


def test_adjust_hf_name_gemma4():
    """gemma4: transformers' names → mlx-lm's (mlp.*, bare layer_scalar)."""
    from vllm_mlx.gguf_convert import _adjust_hf_name

    assert (
        _adjust_hf_name("model.layers.0.feed_forward.up_proj.weight", "gemma4_text")
        == "model.layers.0.mlp.up_proj.weight"
    )
    assert (
        _adjust_hf_name("model.layers.0.layer_scalar.weight", "gemma4_text")
        == "model.layers.0.layer_scalar"
    )
    # Other archs pass through untouched.
    assert (
        _adjust_hf_name("model.layers.0.feed_forward.up_proj.weight", "llama")
        == "model.layers.0.feed_forward.up_proj.weight"
    )


def test_postprocess_norm_minus_one_gating():
    """gemma2/3 norms get −1; gemma4 norms must pass through untouched.

    Measured ground truth: gemma4 GGUF stores raw ``w`` (layers.0
    input_layernorm mean matches google/gemma-4-12B-it to 0.0000), so the
    gemma2/3 +1-fold rule must not fire for gemma4_text.
    """
    from vllm_mlx.gguf_convert import _postprocess_tensor

    w = np.array([0.5, 1.0, 2.0], dtype=np.float32)
    out3 = _postprocess_tensor(w, "model.layers.0.input_layernorm.weight", "gemma3_text", 1, 1)
    np.testing.assert_allclose(out3, w - 1)
    out4 = _postprocess_tensor(w, "model.layers.0.input_layernorm.weight", "gemma4_text", 1, 1)
    np.testing.assert_array_equal(out4, w)


def test_resolve_repo_single_gguf(tmp_path, tiny_gguf):
    fake_hub = tmp_path / "hub"
    fake_hub.mkdir()
    (fake_hub / "model-Q4_K_M.gguf").write_bytes(tiny_gguf.read_bytes())
    with patch("huggingface_hub.snapshot_download", return_value=str(fake_hub)) as dl:
        got = _resolve_source("org/repo")
    dl.assert_called_once_with("org/repo", allow_patterns=["*.gguf"])
    assert got.name == "model-Q4_K_M.gguf"


def test_resolve_repo_multiple_gguf_lists_candidates(tmp_path):
    fake_hub = tmp_path / "hub"
    fake_hub.mkdir()
    (fake_hub / "a-q4.gguf").write_bytes(b"x")
    (fake_hub / "b-q8.gguf").write_bytes(b"x")
    with (
        patch("huggingface_hub.snapshot_download", return_value=str(fake_hub)),
        pytest.raises(ConvertError) as exc,
    ):
        _resolve_source("org/repo")
    msg = str(exc.value)
    assert "a-q4.gguf" in msg and "b-q8.gguf" in msg
    assert "org/repo:<filename>" in msg


def test_resolve_repo_explicit_filename(tmp_path):
    fake_hub = tmp_path / "hub"
    fake_hub.mkdir()
    (fake_hub / "pick-me.gguf").write_bytes(b"x")
    with patch("huggingface_hub.snapshot_download", return_value=str(fake_hub)) as dl:
        got = _resolve_source("org/repo:pick-me.gguf")
    dl.assert_called_once_with("org/repo", allow_patterns=["pick-me.gguf"])
    assert got.name == "pick-me.gguf"


# ----- base-model (strategy ①) acquisition ------------------------------------


def test_base_model_config_and_tokenizer_win(tmp_path):
    """A GGUF with base-model provenance must prefer the base repo's files."""
    gguf_path = tmp_path / "finetune.gguf"
    _write_tiny_gguf(gguf_path, base_repo="base-org/base-model")

    fake_base = tmp_path / "base"
    fake_base.mkdir()
    (fake_base / "config.json").write_text(
        json.dumps(
            {
                "model_type": "llama",
                "num_hidden_layers": _LAYERS,  # must match GGUF block_count
                "_marker": "from-base-repo",
            }
        )
    )
    (fake_base / "tokenizer.json").write_text("{}")
    (fake_base / "generation_config.json").write_text('{"eos_token_id": 99}')

    out = tmp_path / "out"
    with patch("huggingface_hub.snapshot_download", return_value=str(fake_base)) as dl:
        convert_gguf(str(gguf_path), out_dir=out, report=False)
    dl.assert_called_once()
    assert dl.call_args.args[0] == "base-org/base-model"

    cfg = json.loads((out / "config.json").read_text())
    assert cfg["_marker"] == "from-base-repo"
    # torch_dtype is always overridden to the actually-written dtype.
    assert cfg["torch_dtype"] == "bfloat16"
    # Base tokenizer + generation_config were copied, not rebuilt.
    assert (out / "tokenizer.json").read_text() == "{}"
    assert (
        json.loads((out / "generation_config.json").read_text())["eos_token_id"] == 99
    )
    # Weights still came from the GGUF itself.
    assert (out / "model.safetensors").is_file()


# ----- CLI wiring -------------------------------------------------------------


def test_cli_convert_dispatch():
    """`rapid-mlx convert ...` parses and dispatches to convert_command."""
    called = {}

    def fake_convert_command(args):
        called["args"] = args

    argv = [
        "rapid-mlx",
        "--no-telemetry",
        "convert",
        "org/repo:file.gguf",
        "--bits",
        "4",
        "--group-size",
        "32",
        "--dtype",
        "float16",
        "--no-report",
        "-o",
        "/tmp/whatever",
    ]
    with (
        patch.object(sys, "argv", argv),
        patch("vllm_mlx.gguf_convert.convert_command", fake_convert_command),
    ):
        cli.main()

    args = called["args"]
    assert args.command == "convert"
    assert args.source == "org/repo:file.gguf"
    assert args.bits == 4
    assert args.group_size == 32
    assert args.dtype == "float16"
    assert args.report is False
    assert args.output == "/tmp/whatever"


def test_convert_command_error_path_exits_1(tmp_path):
    """A ConvertError surfaces as `Error: …` + exit 1, not a stack trace."""
    buf = io.StringIO()
    args = SimpleNamespace(
        source=str(tmp_path / "missing.gguf"),
        output=None,
        bits=None,
        group_size=64,
        dtype="bfloat16",
        report=None,
    )
    with patch.object(sys, "stdout", buf), pytest.raises(SystemExit) as exc:
        convert_command(args)
    assert exc.value.code == 1
    assert "Error:" in buf.getvalue()


def test_convert_rejects_nonempty_output_dir(tmp_path, tiny_gguf):
    """Refuses to clobber an existing non-empty output directory."""
    out = tmp_path / "occupied"
    out.mkdir()
    (out / "stray.txt").write_text("x")
    with pytest.raises(ConvertError, match="already exists"):
        convert_gguf(str(tiny_gguf), out_dir=out, report=False)


# ----- real-network smoke test (deselected by default) -----------------------


@pytest.mark.slow
def test_convert_real_qwen3_gguf_from_hub(tmp_path):
    """End-to-end against the real ``Qwen/Qwen3-0.6B-GGUF`` (~640 MB download,
    cached by HF afterwards). Exercises HF repo source resolution, Q8_0
    dequantization, qwen3 name mapping (incl. q_norm/k_norm), and the
    ``--bits 4`` requant path. Marked ``slow`` (downloads + loads a real
    model); run explicitly with::

        pytest tests/test_gguf_convert.py --run-slow -m slow
    """
    import mlx_lm

    out = tmp_path / "qwen3-mlx-4bit"
    result = convert_gguf("Qwen/Qwen3-0.6B-GGUF", out_dir=out, bits=4, report=False)
    assert result.tensors_written > 300
    cfg = json.loads((out / "config.json").read_text())
    assert cfg["model_type"] == "qwen3"
    assert cfg.get("quantization", {}).get("bits") == 4

    model, tokenizer = mlx_lm.load(str(out))
    text = mlx_lm.generate(
        model,
        tokenizer,
        prompt="The capital of France is",
        max_tokens=8,
        verbose=False,
    )
    assert "Paris" in text or "paris" in text
