# SPDX-License-Identifier: Apache-2.0
"""
Tests for vllm_mlx/server.py utility functions.

Generated by MiniMax-M2.5 via openclaw simulation, reviewed and fixed by Claude.
"""

from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from vllm_mlx.api.models import FunctionCall, ToolCall
from vllm_mlx.engine.base import GenerationOutput

# ---------------------------------------------------------------------------
# _resolve_temperature / _resolve_top_p
# ---------------------------------------------------------------------------


class TestResolveTemperature:
    """Tests for _resolve_temperature function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.3) == 0.3
        finally:
            cfg.default_temperature = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(None) == 0.8
        finally:
            cfg.default_temperature = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = None
            assert server._resolve_temperature(None) == server._FALLBACK_TEMPERATURE
        finally:
            cfg.default_temperature = old

    def test_zero_is_valid_request_value(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_temperature
        try:
            cfg.default_temperature = 0.8
            assert server._resolve_temperature(0.0) == 0.0
        finally:
            cfg.default_temperature = old


class TestResolveTopP:
    """Tests for _resolve_top_p function."""

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(0.7) == 0.7
        finally:
            cfg.default_top_p = old

    def test_cli_default_over_fallback(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = 0.95
            assert server._resolve_top_p(None) == 0.95
        finally:
            cfg.default_top_p = old

    def test_fallback_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_p
        try:
            cfg.default_top_p = None
            assert server._resolve_top_p(None) == server._FALLBACK_TOP_P
        finally:
            cfg.default_top_p = old


class TestResolveTopK:
    """Tests for _resolve_top_k function.

    Unlike temperature/top_p, top_k has no application-level fallback:
    when both the request and CLI default are unset, the helper returns
    None so the caller skips forwarding and the engine's own
    SamplingParams default applies.
    """

    def test_request_value_takes_priority(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(50) == 50
        finally:
            cfg.default_top_k = old

    def test_cli_default_used_when_request_none(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(None) == 20
        finally:
            cfg.default_top_k = old

    def test_returns_none_when_nothing_set(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = None
            assert server._resolve_top_k(None) is None
        finally:
            cfg.default_top_k = old

    def test_zero_request_value_is_forwarded(self):
        """top_k=0 is a valid disable-top-k signal in some samplers."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        old = cfg.default_top_k
        try:
            cfg.default_top_k = 20
            assert server._resolve_top_k(0) == 0
        finally:
            cfg.default_top_k = old


# ---------------------------------------------------------------------------
# Resolve cascade: alias overlay + generation_config overlay
# ---------------------------------------------------------------------------


class TestResolveCascade:
    """Verify the 4-layer resolve chain:

        request  >  CLI default  >  alias overlay  >  generation_config

    Documented in service/helpers.py::_cascade. We exercise it through
    the public resolve_* helpers because that's the contract route
    handlers actually consume.
    """

    @pytest.fixture(autouse=True)
    def _isolate_config(self):
        """Snapshot/restore the global ServerConfig so cases don't leak."""
        from vllm_mlx.config import get_config

        cfg = get_config()
        snap = {
            "default_temperature": cfg.default_temperature,
            "default_top_p": cfg.default_top_p,
            "default_top_k": cfg.default_top_k,
            "default_min_p": cfg.default_min_p,
            "default_repetition_penalty": cfg.default_repetition_penalty,
            "default_presence_penalty": cfg.default_presence_penalty,
            "default_frequency_penalty": cfg.default_frequency_penalty,
            "alias_recommended_sampling": cfg.alias_recommended_sampling,
            "generation_config_sampling": cfg.generation_config_sampling,
        }
        for k in snap:
            setattr(cfg, k, None)
        yield
        for k, v in snap.items():
            setattr(cfg, k, v)

    def test_temperature_alias_overrides_generation_config(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(None) == 0.5

    def test_temperature_generation_config_used_when_alias_missing(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"temperature": 0.6}
        assert server._resolve_temperature(None) == 0.6

    def test_temperature_cli_default_overrides_overlays(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.default_temperature = 0.9
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(None) == 0.9

    def test_temperature_request_overrides_everything(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.default_temperature = 0.9
        cfg.alias_recommended_sampling = {"temperature": 0.5}
        cfg.generation_config_sampling = {"temperature": 1.0}
        assert server._resolve_temperature(0.1) == 0.1

    def test_top_p_cascade(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"top_p": 0.95}
        assert server._resolve_top_p(None) == 0.95
        cfg.alias_recommended_sampling = {"top_p": 0.8}
        assert server._resolve_top_p(None) == 0.8

    def test_top_k_int_coercion_through_overlay(self):
        """top_k from JSON arrives as int; cascade must preserve type."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.generation_config_sampling = {"top_k": 20}
        assert server._resolve_top_k(None) == 20
        assert isinstance(server._resolve_top_k(None), int)

    def test_min_p_cascade(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        # Layer 4 only
        cfg.generation_config_sampling = {"min_p": 0.05}
        assert server._resolve_min_p(None) == 0.05
        # Layer 3 wins
        cfg.alias_recommended_sampling = {"min_p": 0.1}
        assert server._resolve_min_p(None) == 0.1
        # Layer 2 wins
        cfg.default_min_p = 0.2
        assert server._resolve_min_p(None) == 0.2
        # Layer 1 wins
        assert server._resolve_min_p(0.3) == 0.3

    def test_repetition_penalty_returns_none_when_nothing_set(self):
        from vllm_mlx import server

        assert server._resolve_repetition_penalty(None) is None

    def test_repetition_penalty_alias_layer(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"repetition_penalty": 1.1}
        assert server._resolve_repetition_penalty(None) == 1.1

    def test_presence_penalty_request_layer(self):
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"presence_penalty": 0.5}
        # request value wins even when negative
        assert server._resolve_presence_penalty(-0.2) == -0.2

    def test_frequency_penalty_no_signal_returns_none(self):
        from vllm_mlx import server

        assert server._resolve_frequency_penalty(None) is None

    def test_overlay_dict_can_be_empty(self):
        """Empty overlay dicts must be treated as "no value at this layer"."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {}
        cfg.generation_config_sampling = {}
        assert server._resolve_top_k(None) is None
        assert server._resolve_min_p(None) is None

    def test_zero_request_value_is_forwarded(self):
        """0 is a valid request signal for min_p/penalties — must not be
        confused with "unset" by the cascade."""
        from vllm_mlx import server
        from vllm_mlx.config import get_config

        cfg = get_config()
        cfg.alias_recommended_sampling = {"min_p": 0.1}
        assert server._resolve_min_p(0.0) == 0.0


# ---------------------------------------------------------------------------
# get_usage
# ---------------------------------------------------------------------------


class TestGetUsage:
    """Tests for get_usage function."""

    def test_full_attributes(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(
            text="hello",
            tokens=[1, 2],
            prompt_tokens=100,
            completion_tokens=50,
        )
        usage = get_usage(output)
        assert usage.prompt_tokens == 100
        assert usage.completion_tokens == 50
        assert usage.total_tokens == 150

    def test_default_values(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="hello")
        usage = get_usage(output)
        assert usage.prompt_tokens == 0
        assert usage.completion_tokens == 0
        assert usage.total_tokens == 0

    def test_only_prompt_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", prompt_tokens=200)
        usage = get_usage(output)
        assert usage.prompt_tokens == 200
        assert usage.total_tokens == 200

    def test_only_completion_tokens(self):
        from vllm_mlx.server import get_usage

        output = GenerationOutput(text="x", completion_tokens=75)
        usage = get_usage(output)
        assert usage.completion_tokens == 75
        assert usage.total_tokens == 75


# ---------------------------------------------------------------------------
# _inject_json_instruction
# ---------------------------------------------------------------------------


class TestInjectJsonInstruction:
    """Tests for _inject_json_instruction function."""

    def test_prepend_to_existing_system_dict(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [
            {"role": "system", "content": "You are helpful."},
            {"role": "user", "content": "Hello"},
        ]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert result[0]["content"].startswith("Respond in JSON.\n\n")
        assert "You are helpful." in result[0]["content"]
        assert len(result) == 2

    def test_prepend_to_existing_system_object(self):
        from vllm_mlx.server import _inject_json_instruction

        class Msg:
            def __init__(self, role, content):
                self.role = role
                self.content = content

        messages = [Msg("system", "You are helpful."), Msg("user", "Hi")]
        result = _inject_json_instruction(messages, "JSON only.")

        assert result[0].content.startswith("JSON only.\n\n")
        assert "You are helpful." in result[0].content

    def test_create_system_when_missing(self):
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hello"}]
        result = _inject_json_instruction(messages, "Respond in JSON.")

        assert len(result) == 2
        assert result[0]["role"] == "system"
        assert result[0]["content"] == "Respond in JSON."

    def test_empty_messages(self):
        from vllm_mlx.server import _inject_json_instruction

        result = _inject_json_instruction([], "JSON.")
        assert len(result) == 1
        assert result[0]["content"] == "JSON."

    def test_does_not_mutate_list_length(self):
        """Original list should not gain/lose elements."""
        from vllm_mlx.server import _inject_json_instruction

        messages = [{"role": "user", "content": "Hi"}]
        result = _inject_json_instruction(messages, "JSON.")
        assert len(messages) == 1  # original unchanged
        assert len(result) == 2  # result has new system msg


# ---------------------------------------------------------------------------
# _extract_token_logprob
# ---------------------------------------------------------------------------


class TestExtractTokenLogprob:
    """Tests for _extract_token_logprob function."""

    def _make_logprobs(self, vocab_size=100, token_logprobs=None):
        """Create a mock mx.array with specific token logprobs."""
        arr = np.full(vocab_size, -10.0)  # low default
        if token_logprobs:
            for tid, lp in token_logprobs.items():
                arr[tid] = lp
        mock = MagicMock()
        mock.astype.return_value = mock
        return mock, arr

    def test_basic_top_k(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1, 10: -0.5, 20: -1.0})
        tok = MagicMock()
        tok.decode.side_effect = lambda ids: f"t{ids[0]}"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=3)

        assert result.token == "t5"
        assert result.logprob == pytest.approx(-0.1)
        assert len(result.top_logprobs) == 3
        # Sorted descending
        lps = [t.logprob for t in result.top_logprobs]
        assert lps == sorted(lps, reverse=True)

    def test_top_k_capped_at_vocab(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=100)
        assert len(result.top_logprobs) == 10

    def test_out_of_bounds_token_id(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=500, tokenizer=tok, top_k=3)
        assert result.logprob == 0.0

    def test_bytes_field_populated(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(100, {5: -0.1})
        tok = MagicMock()
        tok.decode.return_value = "hello"

        with patch("numpy.array", return_value=arr):
            result = _extract_token_logprob(mock, token_id=5, tokenizer=tok, top_k=1)
        assert result.bytes == list(b"hello")

    def test_astype_called_for_conversion(self):
        from vllm_mlx.server import _extract_token_logprob

        mock, arr = self._make_logprobs(10)
        tok = MagicMock()
        tok.decode.return_value = "x"

        with patch("numpy.array", return_value=arr):
            _extract_token_logprob(mock, token_id=0, tokenizer=tok, top_k=1)
        mock.astype.assert_called_once()


# ---------------------------------------------------------------------------
# _extract_streaming_token_logprobs (regression for #220)
# ---------------------------------------------------------------------------


class TestExtractStreamingTokenLogprobs:
    """Regression for #220 — under stream_interval > 1 a single chunk
    carries a list[mx.array] of merged per-step distributions, one per
    token in the merged window. The downstream SSE consumer must see
    one TokenLogProb entry per generated token, not one per flush.

    Pre-#220, the chat-route handler passed the entire list to
    ``_extract_token_logprob`` as one flattened array, producing
    misaligned top-k indices and a single under-counted entry.
    """

    def _make_chunk(self, logprobs, new_text="hi", new_token_ids=None, tokens=None):
        from types import SimpleNamespace

        return SimpleNamespace(
            logprobs=logprobs,
            new_text=new_text,
            new_token_ids=new_token_ids,
            tokens=tokens or [],
        )

    def _make_logprob_array(self, vocab_size=64):
        arr = np.full(vocab_size, -10.0)
        arr[0] = -0.1
        mock = MagicMock()
        mock.astype.return_value = mock
        return mock, arr

    def test_single_array_yields_one_entry(self):
        """Backward-compat — stream_interval=1 still gives one entry."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock, arr = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"
        chunk = self._make_chunk(logprobs=mock, new_token_ids=[7], tokens=[7])

        with patch("numpy.array", return_value=arr):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 1

    def test_list_of_three_yields_three_entries(self):
        """The bug — under stream_interval=4, a 3-token flush carries a
        3-element list and must produce 3 separate TokenLogProb entries.
        """
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock_a, arr_a = self._make_logprob_array()
        mock_b, arr_b = self._make_logprob_array()
        mock_c, arr_c = self._make_logprob_array()
        tok = MagicMock()
        tok.decode.return_value = "x"
        chunk = self._make_chunk(
            logprobs=[mock_a, mock_b, mock_c],
            new_token_ids=[10, 11, 12],
            tokens=[10, 11, 12],
        )

        with patch("numpy.array", side_effect=[arr_a, arr_b, arr_c]):
            result = _extract_streaming_token_logprobs(chunk, tok, top_k=3)

        assert len(result) == 3, (
            "Expected one TokenLogProb per merged step; pre-fix this "
            "returned a single entry per flush"
        )

    def test_list_pairs_with_new_token_ids(self):
        """Each per-step distribution must be paired with the matching
        ``new_token_ids[i]``, not always the last token in ``tokens``."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock_a, arr_a = self._make_logprob_array()
        mock_b, arr_b = self._make_logprob_array()
        mock_a.astype.return_value = mock_a
        mock_b.astype.return_value = mock_b

        observed_token_ids = []
        tok = MagicMock()

        def fake_decode(ids):
            observed_token_ids.append(ids[0])
            return f"t{ids[0]}"

        tok.decode.side_effect = fake_decode

        chunk = self._make_chunk(
            logprobs=[mock_a, mock_b],
            new_token_ids=[20, 21],
            tokens=[10, 11, 20, 21],
        )

        with patch("numpy.array", side_effect=[arr_a, arr_b]):
            _extract_streaming_token_logprobs(chunk, tok, top_k=1)

        # The sampled token decoded for each entry must come from
        # new_token_ids, not from chunk.tokens[-1] (= 21 for both).
        sampled = [tid for tid in observed_token_ids if tid in (20, 21)]
        assert sampled == [20, 21], (
            f"Per-step token IDs must come from new_token_ids; got {sampled}"
        )

    def test_empty_chunk_returns_empty(self):
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        chunk = self._make_chunk(logprobs=None)
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []

    def test_no_new_text_returns_empty(self):
        """A chunk without new_text (e.g. empty tool-call passthrough)
        produces no logprobs entries even if logprobs is set."""
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        mock, _ = self._make_logprob_array()
        chunk = self._make_chunk(logprobs=mock, new_text="")
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []

    def test_empty_list_returns_empty(self):
        from vllm_mlx.service.helpers import _extract_streaming_token_logprobs

        chunk = self._make_chunk(logprobs=[], new_text="hi", new_token_ids=[])
        assert _extract_streaming_token_logprobs(chunk, MagicMock(), top_k=3) == []


# ---------------------------------------------------------------------------
# _validate_tool_call_params
# ---------------------------------------------------------------------------


class TestValidateToolCallParams:
    """Tests for _validate_tool_call_params function."""

    def _make_tools(self, name="get_weather", properties=None):
        if properties is None:
            properties = {"location": {"type": "string"}}
        return [
            {
                "type": "function",
                "function": {
                    "name": name,
                    "parameters": {
                        "type": "object",
                        "properties": properties,
                    },
                },
            }
        ]

    def _make_tool_calls(self, name="get_weather", arguments='{"location": "NYC"}'):
        return [
            ToolCall(
                id="call_1",
                type="function",
                function=FunctionCall(name=name, arguments=arguments),
            )
        ]

    def test_valid_args_no_error(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(),
            self._make_tools(),
        )

    def test_invalid_json_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments="not json {"),
            self._make_tools(),
        )

    def test_type_mismatch_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments='{"location": 123}'),
            self._make_tools(properties={"location": {"type": "string"}}),
        )

    def test_enum_violation_no_crash(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params(
            self._make_tool_calls(arguments='{"unit": "kelvin"}'),
            self._make_tools(
                properties={
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                }
            ),
        )

    def test_empty_tool_calls(self):
        from vllm_mlx.server import _validate_tool_call_params

        _validate_tool_call_params([], self._make_tools())

    def test_pydantic_model_tools(self):
        """Test with Pydantic model tools (have model_dump)."""
        from pydantic import BaseModel

        from vllm_mlx.server import _validate_tool_call_params

        class ToolDef(BaseModel):
            type: str = "function"
            function: dict

        tools = [
            ToolDef(
                function={
                    "name": "get_weather",
                    "parameters": {
                        "type": "object",
                        "properties": {"location": {"type": "string"}},
                    },
                }
            )
        ]
        _validate_tool_call_params(
            self._make_tool_calls(),
            tools,
        )


# ---------------------------------------------------------------------------
# extract_json_from_response guard tests
# ---------------------------------------------------------------------------


class TestExtractJsonFromResponse:
    """Tests for extract_json_from_response showing why guard is needed."""

    def test_extracts_json_from_reasoning_text(self):
        """Correctly extracts JSON from reasoning prefix."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = 'Let me think... {"result": 42}'
        assert extract_json_from_response(text) == '{"result": 42}'

    def test_corrupts_plain_text_ending_with_json(self):
        """Without guard, plain text ending with JSON-like braces gets corrupted.

        This documents why server.py wraps the call with `if response_format`.
        """
        from vllm_mlx.api.utils import extract_json_from_response

        # Plain text that happens to end with balanced braces
        plain = 'The config looks like {"debug": true}'
        result = extract_json_from_response(plain)
        # The function extracts '{"debug": true}' — losing the prefix
        assert result == '{"debug": true}'
        assert result != plain

    def test_returns_original_when_no_json(self):
        """Returns original text when no JSON structure found."""
        from vllm_mlx.api.utils import extract_json_from_response

        text = "Hello, world!"
        assert extract_json_from_response(text) == text


# ---------------------------------------------------------------------------
# configure_logging — quiet chatty third-party loggers
# ---------------------------------------------------------------------------


class TestConfigureLogging:
    """Verify chatty transport-layer loggers are silenced at INFO/WARNING but
    not at DEBUG, so HF Hub / httpx noise doesn't drown out startup."""

    @pytest.fixture(autouse=True)
    def _reset_loggers(self):
        import logging as _logging

        names = ("httpx", "httpcore", "urllib3", "huggingface_hub")
        saved = {n: _logging.getLogger(n).level for n in names}
        yield
        for n, lvl in saved.items():
            _logging.getLogger(n).setLevel(lvl)

    def test_info_silences_chatty_loggers(self):
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("INFO")
        for name in ("httpx", "httpcore", "urllib3", "huggingface_hub"):
            assert _logging.getLogger(name).level == _logging.WARNING

    def test_debug_lets_chatty_loggers_through(self):
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("DEBUG")
        for name in ("httpx", "httpcore", "urllib3", "huggingface_hub"):
            assert _logging.getLogger(name).level == _logging.NOTSET

    def test_idempotent_across_level_toggles(self):
        """INFO → DEBUG → INFO must reset chatty loggers each time."""
        import logging as _logging

        from vllm_mlx import server

        server.configure_logging("INFO")
        assert _logging.getLogger("httpx").level == _logging.WARNING
        server.configure_logging("DEBUG")
        assert _logging.getLogger("httpx").level == _logging.NOTSET
        server.configure_logging("INFO")
        assert _logging.getLogger("httpx").level == _logging.WARNING
