#!/usr/bin/env python3.12
"""Repo-wide rewrite of legacy alias names to canonical explicit names.

Loads ``scripts/rename_map.json`` (generated by ``rename_aliases.py``) and
applies the mapping inside every active source file.

EXCLUDED on purpose:
  * ``evals/results/*.json`` — historical benchmark snapshots; their
    ``model`` field records *which alias the bench was run under at the
    time*. Rewriting these is rewriting history.
  * ``CHANGELOG.md`` (if present) — historical release notes; same logic.
  * ``.git/``, ``.build/``, ``.venv/``, ``__pycache__/``, ``node_modules/``
  * ``vllm_mlx/aliases.json`` — already correctly written by
    ``rename_aliases.py``.
  * ``scripts/rename_aliases.py``, ``scripts/rename_map.json``,
    ``scripts/sweep_alias_refs.py`` — these files document the rename
    itself; legacy names must appear in them by construction.

Run from repo root:

    python3.12 scripts/sweep_alias_refs.py [--dry-run]
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RENAME_MAP_PATH = ROOT / "scripts" / "rename_map.json"

# File extensions we sweep.
EXTENSIONS = {
    ".py",
    ".md",
    ".sh",
    ".yaml",
    ".yml",
    ".toml",
    ".cfg",
    ".rst",
    ".mdx",
    ".json",
    ".txt",
}

# Path prefixes to ignore entirely.
SKIP_DIR_PARTS = {
    ".git",
    ".build",
    ".venv",
    "venv",
    "__pycache__",
    "node_modules",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "dist",
    "build",
    ".tox",
    ".claude",
}

# Specific files to leave alone — see module docstring.
SKIP_FILES = {
    ROOT / "vllm_mlx" / "aliases.json",
    ROOT / "scripts" / "rename_aliases.py",
    ROOT / "scripts" / "rename_map.json",
    ROOT / "scripts" / "sweep_alias_refs.py",
    ROOT / "CHANGELOG.md",
}

# Specific subtrees to leave alone.
SKIP_TREES = (
    ROOT / "evals" / "results",
    # Historical doctor harness runs — directory names are
    # ``YYYY-MM-DD-<seq>-<tier>`` and the contents are point-in-time
    # snapshots of what each alias produced. Rewriting them is
    # rewriting history. The ``harness/scorecard/latest.md`` pointer
    # OUTSIDE this tree is intentionally not skipped — it's the live
    # dashboard and will be regenerated on the next ``make check``.
    ROOT / "harness" / "runs",
    # Historical README-refresh benchmark snapshots — captured to
    # justify a release-time README edit; rewriting changes what we
    # claimed at the time.
    ROOT / "reports" / "benchmarks",
    # Historical Model Harness Index reports — filenames have a
    # timestamp suffix (``alias_YYYYMMDD_HHMMSS.json``); rewriting
    # the ``model`` field inside changes which alias the historical
    # MHI score was attributed to.
    ROOT / "reports" / "mhi",
)


def should_skip(path: Path) -> bool:
    if path.is_dir():
        return any(part in SKIP_DIR_PARTS for part in path.parts)
    if path in SKIP_FILES:
        return True
    if any(part in SKIP_DIR_PARTS for part in path.parts):
        return True
    for tree in SKIP_TREES:
        try:
            path.relative_to(tree)
            return True
        except ValueError:
            pass
    if path.suffix not in EXTENSIONS:
        return True
    return False


def build_pattern(rename_map: dict[str, str]) -> re.Pattern:
    """Build one big regex matching any legacy alias on a word boundary.

    Sort by length descending so longer names match before any prefix
    of theirs (e.g. ``qwen3.5-122b`` must match before ``qwen3.5-1``).
    """
    keys = sorted(rename_map.keys(), key=len, reverse=True)
    # Custom boundary: the names contain ``-`` and ``.`` so the stdlib
    # ``\b`` doesn't apply cleanly. Match negative-lookahead/lookbehind
    # against ``[A-Za-z0-9._-]`` — i.e. don't extend on either side.
    parts = [re.escape(k) for k in keys]
    return re.compile(
        r"(?<![A-Za-z0-9._-])(" + "|".join(parts) + r")(?![A-Za-z0-9._-])"
    )


def rewrite_file(
    path: Path, pattern: re.Pattern, rename_map: dict[str, str]
) -> tuple[bool, int]:
    try:
        original = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, PermissionError):
        return False, 0
    count = 0

    def sub(m: re.Match) -> str:
        nonlocal count
        count += 1
        return rename_map[m.group(1)]

    new = pattern.sub(sub, original)
    if new != original:
        return True, count, new
    return False, 0, original


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report files that would change, don't write",
    )
    args = parser.parse_args()

    rename_map = json.loads(RENAME_MAP_PATH.read_text())
    # Filter to entries with a real target (drops + renames).
    rename_map = {o: n for o, n in rename_map.items() if n}
    # High-ambiguity legacy aliases that collide with non-alias usage
    # elsewhere in the codebase. ``gemma4`` is the parser ID
    # (registered in ``gemma4_tool_parser.py``, referenced from
    # ``model_auto_config.py``, ``output_router.py``, etc.) — auto-
    # rewriting it would corrupt the parser registry, so the sweep
    # leaves every occurrence of ``gemma4`` untouched. The matching
    # codename alias was removed from ``aliases.json`` by
    # ``rename_aliases.py``; any remaining alias-context usage (e.g.
    # ``rapid-mlx serve gemma4``) is a manual edit, NOT something this
    # script will rewrite. Rerunning this script on a fresh checkout is
    # therefore intentionally a no-op for ``gemma4``.
    HAND_HANDLED = {"gemma4"}
    rename_map = {o: n for o, n in rename_map.items() if o not in HAND_HANDLED}

    pattern = build_pattern(rename_map)

    changed_files = []
    total_replacements = 0

    for path in ROOT.rglob("*"):
        if should_skip(path):
            continue
        if not path.is_file():
            continue
        try:
            original = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, PermissionError):
            continue
        count = 0

        def sub(m: re.Match) -> str:
            nonlocal count
            count += 1
            return rename_map[m.group(1)]

        new = pattern.sub(sub, original)
        if new != original:
            changed_files.append((path, count))
            total_replacements += count
            if not args.dry_run:
                path.write_text(new, encoding="utf-8")

    rel_root = ROOT
    print(f"  files changed: {len(changed_files)}")
    print(f"  total replacements: {total_replacements}")
    if args.dry_run:
        print("  (dry-run — no files written)")
    print()
    for path, count in sorted(changed_files, key=lambda x: -x[1])[:20]:
        rel = path.relative_to(rel_root)
        print(f"    {count:4d}  {rel}")
    if len(changed_files) > 20:
        print(f"    ... +{len(changed_files) - 20} more")

    return 0


if __name__ == "__main__":
    sys.exit(main())
