#!/usr/bin/env python3
"""Structurally verify the deterministic Rapid-MLX DMG Finder layout.

The DMG install-page layout (icon positions, window bounds, icon size and
volume-relative background picture) is packaged from a committed, versioned
`.DS_Store` template rather than being written by Finder. On macOS 26 Finder
AppleEvents against a mounted volume intermittently hang or silently fail to
persist the `.DS_Store`, so the release path must not depend on them. This
validator parses the template (or any produced `.DS_Store`) directly and
asserts it matches the declared layout:

  - exactly one browser-window-settings (`bwsp`) record in Finder's own
    schema (a ``WindowBounds`` string plus the sidebar/toolbar switches),
  - exactly one icon-view (`icvp`) record with image backgroundType, the
    ``backgroundColor*`` triple Finder needs before it applies the record at
    all, the expected icon/text metrics, and a background alias that targets
    ``.background/background.png`` on the ``/Volumes/Rapid-MLX Desktop``
    mount point (the only way Finder resolves it — by path, not CNID),
  - an icon-view (`icvl` = ``icnv``) view-mode record,
  - icon-position (`Iloc`) records for exactly the three volume items
    (``Rapid-MLX Desktop.app``, ``Applications`` and ``.background``) at the
    expected spots, with ``.background`` parked below the window's fold,
  - no build-host / temp-mount strings anywhere in the file, so the template
    stays deterministic and remountable on any machine. The canonical mount
    point ``/Volumes/Rapid-MLX Desktop`` is derived from the volume name, not
    the host, and is required (see above) rather than forbidden.

Both plist records must be *flat* bplists whose root object is a dictionary,
exactly as Finder writes them. A bplist nested inside another bplist as a
``<data>`` object — which is what ``ds_store`` produces when handed
pre-serialised bytes instead of a dict — is rejected: Finder on macOS 14 and
26.6 aborts with ``-[__NSCFData count]: unrecognized selector`` when it opens
such a volume (#3468). The template is generated by ``make-dmg-layout.py``.

Threat model. This gate catches *accidental* regressions in the deterministic
template produced by ``make-dmg-layout.py`` -- a reintroduced nested-plist
encoding (#3468), a dropped ``backgroundColor`` triple, a missing mount-point
tag, a wrong icon position, a lost ``icvl``. It is not, and need not be, a
defence against a deliberately hand-crafted malformed ``.DS_Store``: the only
way such a file reaches this check is by committing it to the repository, and
an attacker who can do that can equally edit this verifier, so the gate is not
a trust boundary against them. The template's sole producer is the generator,
whose output is byte-reproducible and verified here and by the hermetic tests.

Given that, the gate is deliberately standard-library only: the release
scripts invoke it as plain ``python3 verify-dmg-layout.py`` (see
configure-dmg-layout.sh and validate-dmg.sh, both asserted by
DMGPresentationScriptTests), so it must not depend on ``ds_store``/``mac_alias``
or fetch anything at release time. It therefore byte-scans for records rather
than parsing the buddy-allocator B-tree. Against the realistic regressions it
verifies the nested-plist encoding directly, requires the render-critical
fields, and rejects a marker fabricated inside another ``.`` record's value
(``_all_dot_payload_spans`` + ``_assert_top_level``). What a byte-scan cannot
prove is B-tree *reachability*: a marker sitting in unallocated file space, or
in a record owned by a name other than ``.``, is indistinguishable from a real
leaf entry without walking the tree. Closing that residue would mean
enumerating the real B-tree with ``ds_store`` (the module the generator
already uses); that is intentionally not done here to keep the release gate
dependency-free, since such inputs fall outside the accidental-regression
threat model above.

Usage: scripts/verify-dmg-layout.py /path/to/.DS_Store
"""

from __future__ import annotations

import math
import plistlib
import struct
import sys
from pathlib import Path
from typing import NamedTuple


class _Record(NamedTuple):
    """A located ``.DS_Store`` record and the byte span it occupies.

    ``marker_start`` is where the (anchored) code/type marker begins;
    ``end`` is one past the record's last byte. ``payload`` is the record's
    value bytes (empty for the fixed-width ``icvl`` type record).
    """

    marker_start: int
    end: int
    payload: bytes


ILOC_BLOB_MARKER = b"Ilocblob"
# ``icvl`` is a 4-byte ``type`` record, not a blob: code + type + OSType value.
ICVL_TYPE_RECORD = b"icvltypeicnv"

# A .DS_Store B-tree leaf record is laid out as
# ``<nlen:>I><name:utf16be><structure-id:4s><data-type:4s><value>``. The
# ``bwsp``/``icvp``/``icvl`` records all belong to the root ``.`` entry, so a
# real record's structure id is always immediately preceded by the ``.`` leaf
# header: an ``nlen`` of 1 followed by ``.`` in UTF-16BE. Anchoring the marker
# scan to this header attributes each hit to an actual B-tree record instead
# of matching the same bytes where they happen to occur inside another
# record's payload — which would otherwise let a .DS_Store carrying no real
# ``icvp``/``icvl`` record still pass, since Finder reads the B-tree, not the
# raw bytes (#3468 review hardening).
DOT_LEAF_HEADER = b"\x00\x00\x00\x01\x00."

# The committed template (generated with the `ds_store`/`mac_alias` modules)
# stores the HFS path with plain ``:`` separators --
# "Rapid-MLX Desktop:.background:background.png" -- while some Finder-written
# files insert a ``\x00`` before the filename ("...:.background:\x00background.png").
# Both encode the same volume-relative target, so the HFS path is compared
# after normalising any ``\x00`` away. The POSIX path is compared exactly.
EXPECTED_HFS_PATH = b"Rapid-MLX Desktop:.background:background.png"
EXPECTED_POSIX_PATH = b"/.background/background.png"
# Alias tag 0x0013. Finder resolves the background as <mount point> +
# <POSIX path>; without this tag the alias never resolves and the install
# page opens without its artwork (measured on macOS 26.5 against dmgbuild's
# output as the reference).
EXPECTED_MOUNT_POINT = b"/Volumes/Rapid-MLX Desktop"
ALIAS_FIXED_HEADER_SIZE = 150

# Expected positions: app | Applications | iconSize | window bounds. This is
# the same contract the old Finder readback compared against:
#   "180,228|540,228|96|180,120,900,580"
# (window bounds are expressed in bwsp as WindowBounds "{{x, y}, {w, h}}").
EXPECTED_APP_POSITION = (180, 228)
EXPECTED_APPLICATIONS_POSITION = (540, 228)

# ``.background`` holds the window wallpaper and is support data, not something
# the user should ever drag. A dot-prefixed name is hidden from Finder only
# while the viewer keeps the default "don't show hidden files" setting; with
# ``AppleShowAllFiles=1`` Finder draws it, and no file flag suppresses that
# (neither ``chflags hidden`` nor the kIsInvisible FinderInfo bit — both were
# measured against a live Finder). Without an explicit Iloc, Finder auto-grids
# it into the first free cell, which for a 96pt icon size is the top-left of
# the window — squarely on top of the branded artwork.
#
# So park it below the fold instead. An Iloc is the icon's centre, so with a
# 96pt icon and a 460pt-tall window (``EXPECTED_BOUNDS``) the template ships it
# at (100, 560): the icon top lands ~512pt down and cannot intrude on the
# visible install page. This mirrors the below-fold support-item pattern used
# by other shipped installer DMGs. The position is verified as "below the
# fold" rather than pinned to this exact pair — see the icon-position block in
# verify().
EXPECTED_ICON_SIZE = 96.0
EXPECTED_TEXT_SIZE = 13.0
EXPECTED_BOUNDS = {"left": 180, "top": 120, "right": 900, "bottom": 580}
EXPECTED_WINDOW_BOUNDS = "{{180, 120}, {720, 460}}"
# Finder chrome that must be off so the install page is a bare icon window.
EXPECTED_BWSP_SWITCHES = {
    "ContainerShowSidebar": False,
    "PreviewPaneVisibility": False,
    "ShowPathbar": False,
    "ShowSidebar": False,
    "ShowStatusBar": False,
    "ShowTabView": False,
    "ShowToolbar": False,
}

# Substrings that would make the template non-deterministic across hosts or
# bind it to a specific build mount. A .DS_Store carrying any of these must be
# rejected: the layout must stay remountable anywhere. The canonical
# ``/Volumes/Rapid-MLX Desktop`` mount point is deliberately NOT in this list —
# the alias must carry it (EXPECTED_MOUNT_POINT) — but a suffixed variant such
# as ``/Volumes/Rapid-MLX Desktop 1`` (what macOS assigns when the name is
# already taken during a build) is.
FORBIDDEN_SUBSTRINGS = (
    b"rapid-dmg-layout-",
    b"/tmp/",
    b"/var/folders/",
    b"raullenstudio",
    b"/Volumes/Rapid-MLX Desktop ",
)


def _load_bplist(payload: bytes, record: str) -> dict:
    """Load a flat bplist record and require a dictionary root.

    Finder reads these records straight into an ``NSDictionary``. If the root
    object is anything else — in particular a ``<data>`` blob holding another
    bplist, the shape the 0.14.0–0.14.2 template shipped — Finder on macOS 14
    and 26.6 dies with ``-[__NSCFData count]: unrecognized selector`` the
    moment the volume is opened (#3468). Never unwrap; reject.
    """
    try:
        value = plistlib.loads(payload)
    except Exception as exc:  # plistlib raises several unrelated types
        raise ValueError(f"{record} record is not a valid bplist: {exc}") from exc
    if isinstance(value, (bytes, bytearray)):
        nested = bytes(value).startswith(b"bplist00")
        raise ValueError(
            f"{record} record root is <data>"
            + (" wrapping another bplist" if nested else "")
            + ", not a dict — Finder crashes on this encoding (#3468)"
        )
    if not isinstance(value, dict):
        raise ValueError(f"{record} record root is {type(value).__name__}, not a dict")
    return value


def _find_records(data: bytes, marker: bytes) -> list[bytes]:
    """Return the raw payload of every ``<marker><len><payload>`` record."""
    records: list[bytes] = []
    cursor = 0
    while True:
        marker_pos = data.find(marker, cursor)
        if marker_pos < 0:
            return records
        length_offset = marker_pos + len(marker)
        payload_offset = length_offset + 4
        if payload_offset > len(data):
            raise ValueError(f"{marker.decode()} length field is truncated")
        payload_length = struct.unpack(">I", data[length_offset:payload_offset])[0]
        payload = data[payload_offset : payload_offset + payload_length]
        if len(payload) != payload_length:
            raise ValueError(f"{marker.decode()} blob payload is truncated")
        records.append(payload)
        cursor = marker_pos + 1


def _find_dot_blob_records(data: bytes, code: bytes) -> list[_Record]:
    """Every root-``.`` ``<code>blob`` record with its byte span.

    The marker is anchored to the ``.`` leaf header (see ``DOT_LEAF_HEADER``)
    so a copy of ``<code>blob`` occurring inside another record's payload is
    not mistaken for a structural record; ``_assert_top_level`` then rejects
    the residual case where the whole anchored marker is embedded in a value.
    """
    marker = DOT_LEAF_HEADER + code + b"blob"
    records: list[_Record] = []
    cursor = 0
    while True:
        marker_pos = data.find(marker, cursor)
        if marker_pos < 0:
            return records
        length_offset = marker_pos + len(marker)
        payload_offset = length_offset + 4
        if payload_offset > len(data):
            raise ValueError(f"{code.decode()} length field is truncated")
        payload_length = struct.unpack(">I", data[length_offset:payload_offset])[0]
        payload = data[payload_offset : payload_offset + payload_length]
        if len(payload) != payload_length:
            raise ValueError(f"{code.decode()} blob payload is truncated")
        records.append(
            _Record(
                marker_pos + len(DOT_LEAF_HEADER),
                payload_offset + payload_length,
                payload,
            )
        )
        cursor = marker_pos + 1


# Variable-length ``.`` value types whose bytes are large enough to conceal a
# fabricated record (fixed-width types -- long/shor/type/bool/comp/dutc, all
# <=8 bytes -- cannot). ``blob`` and ``ustr`` both prefix their value with a
# big-endian u32 count; ``ustr`` counts UTF-16 code units (2 bytes each).
_VAR_LEN_VALUE_UNIT = {b"blob": 1, b"ustr": 2}


def _all_dot_payload_spans(data: bytes) -> list[tuple[int, int]]:
    """Payload byte spans of every variable-length root-``.`` record.

    Enumerates each ``.`` leaf header, reads its 4-byte structure id and data
    type, and for the variable-length types records the byte range the value
    occupies. ``_assert_top_level`` treats these as forbidden regions for
    structural markers, so a fabricated ``icvp``/``icvl`` (or ``bwsp``) hidden
    inside *any* ``.`` value -- recognized or not, e.g. a bogus ``Junk`` blob
    -- is rejected, not just one buried in a record the verifier happens to
    recognize. This closes the residual byte-scan gap where the required
    record exists only as bytes embedded in an unrecognized entry, leaving
    Finder to open a blank/default window (#3468 hardening).

    Only ``.`` entries are scanned: every record the template writes is either
    a ``.`` entry or a 16-byte ``Iloc`` (too small to conceal a record). A
    marker smuggled inside a value owned by some *other* filename is not
    covered here; the authoritative defence against that would be a full
    B-tree parse (the `ds_store` module), deliberately not taken so the
    release gate stays standard-library only -- see the module docstring.
    """
    spans: list[tuple[int, int]] = []
    cursor = 0
    while True:
        header_pos = data.find(DOT_LEAF_HEADER, cursor)
        if header_pos < 0:
            return spans
        cursor = header_pos + 1
        count_offset = header_pos + len(DOT_LEAF_HEADER) + 4 + 4  # + code + type
        payload_offset = count_offset + 4
        if payload_offset > len(data):
            continue
        data_type = data[count_offset - 4 : count_offset - 4 + 4]
        unit = _VAR_LEN_VALUE_UNIT.get(data_type)
        if unit is None:
            continue
        count = struct.unpack(">I", data[count_offset:payload_offset])[0]
        end = payload_offset + count * unit
        if end <= len(data):
            spans.append((payload_offset, end))


def _assert_top_level(
    records: list[_Record], payload_spans: list[tuple[int, int]]
) -> None:
    """Reject any record whose marker sits inside another record's payload.

    ``.DS_Store`` B-tree entries are disjoint, so a real record's marker never
    falls within another record's value bytes. This catches the residual
    byte-scan gap: an attacker-crafted or accidentally malformed file that
    buries a fully leaf-header-prefixed marker + payload inside a legitimate
    record's value would otherwise be counted as a structural record even
    though Finder, reading the actual B-tree, never sees it (#3468 hardening).
    """
    for record in records:
        for start, end in payload_spans:
            if start <= record.marker_start < end:
                raise ValueError(
                    "record marker is embedded inside another record's payload "
                    "(not a top-level B-tree entry) — malformed .DS_Store"
                )


def _pascal_string(data: bytes, offset: int, capacity: int, field: str) -> bytes:
    if offset + capacity > len(data):
        raise ValueError(f"alias {field} field is truncated")
    length = data[offset]
    if length >= capacity:
        raise ValueError(f"alias {field} length exceeds its fixed field")
    return data[offset + 1 : offset + 1 + length]


def parse_alias_target(alias: bytes) -> tuple[bytes, bytes, bytes]:
    """Decode the v2 Alias Manager record.

    Returns its HFS path, volume-relative POSIX path and volume mount point.
    """
    if len(alias) < ALIAS_FIXED_HEADER_SIZE + 4:
        raise ValueError("backgroundImageAlias is truncated")
    record_size = struct.unpack(">H", alias[4:6])[0]
    if record_size != len(alias):
        raise ValueError(
            f"backgroundImageAlias size field is {record_size}, actual {len(alias)}"
        )
    if struct.unpack(">H", alias[6:8])[0] != 2:
        raise ValueError("backgroundImageAlias is not a v2 Alias Manager record")
    if struct.unpack(">H", alias[8:10])[0] != 0:
        raise ValueError("backgroundImageAlias does not target a file")

    volume_name = _pascal_string(alias, 10, 28, "volume name")
    file_name = _pascal_string(alias, 50, 64, "file name")
    if volume_name != b"Rapid-MLX Desktop" or file_name != b"background.png":
        raise ValueError("backgroundImageAlias header targets the wrong volume or file")

    cursor = ALIAS_FIXED_HEADER_SIZE
    tags: dict[int, bytes] = {}
    terminated = False
    while cursor + 4 <= len(alias):
        tag, length = struct.unpack(">HH", alias[cursor : cursor + 4])
        cursor += 4
        if tag == 0xFFFF:
            if length != 0 or cursor != len(alias):
                raise ValueError("backgroundImageAlias has an invalid terminator")
            terminated = True
            break
        value_end = cursor + length
        if value_end > len(alias):
            raise ValueError(f"backgroundImageAlias tag 0x{tag:04x} is truncated")
        if tag in tags:
            raise ValueError(f"backgroundImageAlias repeats tag 0x{tag:04x}")
        tags[tag] = alias[cursor:value_end]
        cursor = value_end + (length % 2)

    if not terminated:
        raise ValueError("backgroundImageAlias has no terminator")
    try:
        parent = tags[0x0000]
        hfs_path = tags[0x0002]
        posix_path = tags[0x0012]
        mount_point = tags[0x0013]
    except KeyError as exc:
        raise ValueError(
            f"backgroundImageAlias is missing path tag 0x{exc.args[0]:04x}"
        ) from None
    if parent != b".background":
        raise ValueError("backgroundImageAlias targets the wrong parent directory")
    return hfs_path, posix_path, mount_point


def _iloc_filename(data: bytes, iloc_marker_pos: int) -> str:
    """Attribute an ``Iloc`` record to its owning filename.

    A .DS_Store B-tree leaf record is laid out as::

        <nlen:>I><filename:utf16be><code:4s><type:4s><value>

    The ``Ilocblob`` marker spans ``code``(``Iloc``) + ``type``(``blob``), so
    the UTF-16BE filename's final character ends immediately before the
    marker. Walk backward to find the ``>I`` nlen such that
    ``nlen*2 == marker_pos - (p + 4)``; that pins the filename uniquely.
    """
    for p in range(iloc_marker_pos - 4, max(0, iloc_marker_pos - 400), -1):
        span = iloc_marker_pos - (p + 4)
        if span <= 0 or span % 2:
            continue
        name_len = struct.unpack(">I", data[p : p + 4])[0]
        if name_len * 2 == span and name_len > 0:
            try:
                return data[p + 4 : iloc_marker_pos].decode("utf-16-be")
            except UnicodeDecodeError as exc:
                raise ValueError("Iloc record has a malformed owning filename") from exc
    raise ValueError("Iloc record could not be attributed to a filename")


def _parse_iloc_payload(payload: bytes) -> tuple[int, int]:
    """Decode ``(x, y)`` from an Iloc payload and sanity-check the flags."""
    if len(payload) != 16:
        raise ValueError("Iloc blob payload is not 16 bytes")
    x, y, flag1, flag2 = struct.unpack(">IIII", payload)
    # Third and fourth words are reserved flags; a change to their meaning
    # indicates a different (or corrupted) record layout.
    if flag1 != 0xFFFFFFFF or flag2 != 0xFFFF0000:
        raise ValueError("Iloc blob has unexpected reserved flags")
    return x, y


def verify(path: Path) -> None:
    data = path.read_bytes()

    bwsp_records = _find_dot_blob_records(data, b"bwsp")
    if len(bwsp_records) != 1:
        raise ValueError(f"expected exactly one bwsp record, found {len(bwsp_records)}")
    bwsp = _load_bplist(bwsp_records[0].payload, "bwsp")
    bounds = bwsp.get("WindowBounds")
    if bounds != EXPECTED_WINDOW_BOUNDS:
        raise ValueError(
            f"unexpected window bounds {bounds!r}, expected {EXPECTED_WINDOW_BOUNDS!r}"
        )
    for key, expected in EXPECTED_BWSP_SWITCHES.items():
        if bwsp.get(key) is not expected:
            raise ValueError(f"bwsp {key} is {bwsp.get(key)!r}, expected {expected!r}")
    # SidebarWidth is an int, not a bool, so it is checked separately from the
    # switch set above: a bare install window has no sidebar (width 0).
    sidebar_width = bwsp.get("SidebarWidth")
    if sidebar_width != 0:
        raise ValueError(
            f"bwsp SidebarWidth is {sidebar_width!r}, expected 0 "
            "(a bare install window has no sidebar)"
        )

    icvp_records = _find_dot_blob_records(data, b"icvp")
    if len(icvp_records) != 1:
        raise ValueError(f"expected exactly one icvp record, found {len(icvp_records)}")
    icvp = _load_bplist(icvp_records[0].payload, "icvp")
    if icvp.get("backgroundType") != 2:
        raise ValueError("icvp backgroundType is not image mode (2)")
    for channel in (
        "backgroundColorRed",
        "backgroundColorGreen",
        "backgroundColorBlue",
    ):
        value = icvp.get(channel)
        if not isinstance(value, float):
            raise ValueError(
                f"icvp {channel} is missing or not a float — Finder ignores the "
                "whole icvp record (default icon size, no background) without "
                "the colour triple, even in image mode"
            )
        # A finite channel in [0, 1] is the only value Finder renders; NaN,
        # infinities and out-of-range floats satisfy an isinstance check but
        # are not a valid colour, so range-check explicitly (NaN fails every
        # comparison, so `0.0 <= value <= 1.0` also rejects it).
        if not math.isfinite(value) or not 0.0 <= value <= 1.0:
            raise ValueError(
                f"icvp {channel} is {value!r}, not a finite colour component in "
                "[0.0, 1.0]"
            )
    if icvp.get("iconSize") != EXPECTED_ICON_SIZE:
        raise ValueError(
            f"icvp iconSize is {icvp.get('iconSize')!r}, expected {EXPECTED_ICON_SIZE}"
        )
    if icvp.get("textSize") != EXPECTED_TEXT_SIZE:
        raise ValueError(
            f"icvp textSize is {icvp.get('textSize')!r}, expected {EXPECTED_TEXT_SIZE}"
        )
    if icvp.get("showIconPreview") is not True:
        raise ValueError("icvp showIconPreview is not true")
    if icvp.get("showItemInfo") is not False:
        raise ValueError("icvp showItemInfo is not false")
    if icvp.get("labelOnBottom") is not True:
        raise ValueError("icvp labelOnBottom is not true")
    if icvp.get("arrangeBy") != "none":
        raise ValueError(
            f"icvp arrangeBy is {icvp.get('arrangeBy')!r}, expected 'none'"
        )

    alias = icvp.get("backgroundImageAlias")
    if not isinstance(alias, bytes):
        raise ValueError(
            "icvp backgroundImageAlias is missing or not binary alias data"
        )
    hfs_path, posix_path, mount_point = parse_alias_target(alias)
    # Accept both separator variants for the HFS path, then require the exact
    # volume-relative preferences (never an absolute build mount path).
    normalized_hfs = hfs_path.replace(b"\x00", b"")
    if normalized_hfs != EXPECTED_HFS_PATH:
        raise ValueError(
            f"backgroundImageAlias HFS path {hfs_path!r} does not target .background/background.png"
        )
    if posix_path != EXPECTED_POSIX_PATH:
        raise ValueError(
            f"backgroundImageAlias POSIX path {posix_path!r} is not volume-relative"
        )
    if mount_point != EXPECTED_MOUNT_POINT:
        raise ValueError(
            f"backgroundImageAlias mount point {mount_point!r} is not "
            f"{EXPECTED_MOUNT_POINT!r} — Finder resolves the background as "
            "mount point + POSIX path, so a build-time or suffixed mount "
            "leaves the install page without its artwork"
        )

    icvl_marker = DOT_LEAF_HEADER + ICVL_TYPE_RECORD
    icvl_records: list[_Record] = []
    icvl_cursor = 0
    while True:
        marker_pos = data.find(icvl_marker, icvl_cursor)
        if marker_pos < 0:
            break
        icvl_records.append(
            _Record(
                marker_pos + len(DOT_LEAF_HEADER), marker_pos + len(icvl_marker), b""
            )
        )
        icvl_cursor = marker_pos + 1
    if len(icvl_records) != 1:
        raise ValueError(
            f"expected exactly one icon-view icvl record, found {len(icvl_records)}"
        )

    # Collect every Iloc record and attribute each to its owning filename.
    positions: dict[str, tuple[int, int]] = {}
    iloc_records: list[_Record] = []
    iloc_cursor = 0
    while True:
        marker_pos = data.find(ILOC_BLOB_MARKER, iloc_cursor)
        if marker_pos < 0:
            break
        payload = _find_records(data[marker_pos:], ILOC_BLOB_MARKER)[0]
        name = _iloc_filename(data, marker_pos)
        if name in positions:
            raise ValueError(f"duplicate Iloc record for {name!r}")
        positions[name] = _parse_iloc_payload(payload)
        iloc_records.append(
            _Record(
                marker_pos,
                marker_pos + len(ILOC_BLOB_MARKER) + 4 + len(payload),
                payload,
            )
        )
        iloc_cursor = marker_pos + 1

    # No record's marker may lie inside another record's payload: real B-tree
    # entries are disjoint, so this rejects a marker buried in a value even
    # when it carries the full leaf-header prefix (#3468 hardening).
    all_records = [*bwsp_records, *icvp_records, *icvl_records, *iloc_records]
    _assert_top_level(all_records, _all_dot_payload_spans(data))

    if set(positions) != {
        "Rapid-MLX Desktop.app",
        "Applications",
        ".background",
    }:
        raise ValueError(f"unexpected icon positions {positions!r}")

    # The two draggable icons are the install page's design; pin them exactly.
    for name, expected in (
        ("Rapid-MLX Desktop.app", EXPECTED_APP_POSITION),
        ("Applications", EXPECTED_APPLICATIONS_POSITION),
    ):
        if positions[name] != expected:
            raise ValueError(
                f"unexpected icon positions {positions!r} — {name} should be at {expected}"
            )

    # ``.background`` is support data, so what matters is not a specific spot
    # but that Finder cannot draw it on the visible install page. Check that
    # property against the parsed record rather than pinning a coordinate, so
    # the parking spot can move without weakening the guarantee.
    window_height = EXPECTED_BOUNDS["bottom"] - EXPECTED_BOUNDS["top"]
    background_icon_top = positions[".background"][1] - EXPECTED_ICON_SIZE / 2
    if background_icon_top <= window_height:
        raise ValueError(
            f".background is at {positions['.background']}, which puts its icon "
            f"top at {background_icon_top:g} — not below the {window_height}pt "
            "window fold, so it would show on the install page whenever Finder "
            "is set to show hidden files"
        )

    # Determinism / no-host-embedding gate. Any of these means the template was
    # produced against a specific build mount or host and is not shippable.
    for substring in FORBIDDEN_SUBSTRINGS:
        if substring in data:
            raise ValueError(
                f".DS_Store embeds forbidden host/mount string {substring!r}"
            )


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {Path(argv[0]).name} /path/to/.DS_Store", file=sys.stderr)
        return 2
    try:
        verify(Path(argv[1]))
    except (OSError, ValueError) as exc:
        print(f"verify-dmg-layout: FAIL — {exc}", file=sys.stderr)
        return 1
    print("verify-dmg-layout: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
